import os

S3_LOCATION = 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
S3_KEY = 'XXXXXXXXXXXXXXXXX'
S3_SECRET = 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'

S3_BUCKET = 'XXXXXXXXXX'

SECRET_KEY = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'"
DEBUG = True
PORT = 5000